### ISSUE TITLE
add dark terminal support :)

### ISSUE THREAD

**Issue by alvaropinot** [m1ome/peyote#1]
love the thingy, but I have a dark background and the keys are non readable. What a bout a theme for dark terms? :)

**Comment by m1ome** [comment]
@alvaropinot done in `0.2.1` you can update it though `npm install -g peyote`. 

You can use new version though:
```
peyote-dark '{"name": "Username"}'
```
By default `light` version is set up. Hope you like it.

**Comment by alvaropinot** [comment]
OH! awesome!!! thank you @m1ome :D

**Comment by m1ome** [comment]
@alvaropinot you are welcome! Thank you for your interest in peyote.
